export const ACTIONS = { 
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_FAIL: "LOGIN_REQUEST_FAIL",
  LOGOUT: "LOGOUT",

  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_RESET_FAIL: "PASSWORD_RESET_FAIL",
  PASSWORD_RESET_CHECK: "PASSWORD_RESET_CHECK",
}